// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PR.Data;

#nullable disable

namespace PR.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PR.Models.Entities.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovalComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Goals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApprovedBy = 1,
                            Category = 1,
                            CreatedAt = new DateTime(2025, 11, 29, 11, 36, 0, 76, DateTimeKind.Utc).AddTicks(6049),
                            Description = "Grow overall company revenue by expanding market share.",
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Title = "Increase Annual Revenue",
                            UpdatedAt = new DateTime(2025, 11, 29, 11, 36, 0, 76, DateTimeKind.Utc).AddTicks(6052),
                            Weight = 0m
                        },
                        new
                        {
                            Id = 2,
                            ApprovedBy = 1,
                            Category = 1,
                            CreatedAt = new DateTime(2025, 11, 29, 11, 36, 0, 76, DateTimeKind.Utc).AddTicks(6079),
                            Description = "Improve customer onboarding experience and expand reach.",
                            EndDate = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Title = "Enhance Customer Base",
                            UpdatedAt = new DateTime(2025, 11, 29, 11, 36, 0, 76, DateTimeKind.Utc).AddTicks(6081),
                            Weight = 0m
                        },
                        new
                        {
                            Id = 3,
                            ApprovedBy = 1,
                            Category = 1,
                            CreatedAt = new DateTime(2025, 11, 29, 11, 36, 0, 76, DateTimeKind.Utc).AddTicks(6094),
                            Description = "Streamline workflows using automation.",
                            EndDate = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Title = "Improve Internal Processes",
                            UpdatedAt = new DateTime(2025, 11, 29, 11, 36, 0, 76, DateTimeKind.Utc).AddTicks(6096),
                            Weight = 0m
                        });
                });

            modelBuilder.Entity("PR.Models.Entities.KPI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GoalId")
                        .HasColumnType("int");

                    b.Property<string>("MeasurementUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TargetValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("KPIs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MeasurementUnit = "%",
                            Name = "Revenue Growth %"
                        },
                        new
                        {
                            Id = 2,
                            MeasurementUnit = "Count",
                            Name = "Customer Acquisition"
                        },
                        new
                        {
                            Id = 3,
                            MeasurementUnit = "%",
                            Name = "Operational Efficiency"
                        },
                        new
                        {
                            Id = 4,
                            MeasurementUnit = "%",
                            Name = "Employee Satisfaction"
                        });
                });

            modelBuilder.Entity("PR.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 29, 11, 36, 0, 76, DateTimeKind.Utc).AddTicks(4173),
                            Department = "IT",
                            Email = "admin@performancemanagement.com",
                            EmployeeId = "EMP001",
                            FirstName = "System",
                            HireDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "System Administrator",
                            LastName = "Administrator",
                            PasswordHash = "Admin@123",
                            Role = "Admin",
                            UpdatedAt = new DateTime(2025, 11, 29, 11, 36, 0, 76, DateTimeKind.Utc).AddTicks(4176)
                        });
                });

            modelBuilder.Entity("PR.Models.Entities.KPI", b =>
                {
                    b.HasOne("PR.Models.Entities.Goal", null)
                        .WithMany("KPIs")
                        .HasForeignKey("GoalId");
                });

            modelBuilder.Entity("PR.Models.Entities.Goal", b =>
                {
                    b.Navigation("KPIs");
                });
#pragma warning restore 612, 618
        }
    }
}
